### ISSUE TITLE
[CI] flake8 tests do not fail our CI flow. Although they should

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/baboon#130]
Take for example this CI flow:
https://github.com/beyond-io/baboon/pull/125/checks?check_run_id=821379529

Expand  "Lint with flake8", and see that although flake8 failed on some things, the CI passed without noticing this.

**Comment by ipolonsk** [comment]
Hey,
As I see it, there are two problems here:
1. flake8 failed, and the CI is passed
2. flake8 is alarming us about our code style, we need to rewrite it accordingly to the errors codes we get and the style guide:
https://www.flake8rules.com/

**Comment by IlanZuckerman** [comment]
Great! So we definitely need to change the setting from section 1.
We need to fail the CI if our code don't comply with flake8.
Can you please do that?
Regarding section 2, each member who commits PR, need to make sure his code comply with flake8 prior merging to master. That's why we need the CI checks to prevent this.

**Comment by ipolonsk** [comment]
Let take the first issue to an open discussion on Sunday (maybe there are more settings to change).
About the second, we already have a "bad" code style inside our master code, so we need to fix those errors retrospectively, I will do it.

**Comment by Omeramsc** [comment]
I'll fix it. 
Although keep in mind that the CI for the PR will fail.
